services:
  yaml-dataclass-config:
    build: .
    image: futureys/yaml-dataclass-config:latest
    volumes:
      - .:/workspace:cached
      - /workspace/.venv
      # - Using uv in Docker | uv
      #   https://docs.astral.sh/uv/guides/integration/docker/#caching
      - uv-cache:/root/.cache/uv
volumes:
  uv-cache:
